grpc:
  server:
    port: 6565

grpc-server-tls:
  enabled: true
  cert-chain-file-path: "/home/kevintran/SourceCode/Personal/Practice/practice-spring-grpc/sample-grpc-tls-client/certificates/server/cert.pem"
  private-key-file-path: "/home/kevintran/SourceCode/Personal/Practice/practice-spring-grpc/sample-grpc-tls-client/certificates/server/private_key.pkcs8.pem"
# Below is the wrong way because yaml file doesn't allow this
#  cert-chain: >
#-----BEGIN CERTIFICATE-----
#MIIDazCCAlMCFBGaybCAzilZFCXc+gM22zsWLANqMA0GCSqGSIb3DQEBCwUAMHIx
#CzAJBgNVBAYTAkNBMRAwDgYDVQQIDAdPbnRhcmlvMScwJQYDVQQHDB5MZW9uYXJk
#byBXb3JsZHdpZGUgQ29ycG9yYXRpb24xFDASBgNVBAoMC1RlYW0gUm9ja2V0MRIw
#EAYDVQQDDAlsb2NhbGhvc3QwHhcNMTkwNzIyMjAwMjA0WhcNMjkwNzE5MjAwMjA0
#WjByMQswCQYDVQQGEwJDQTEQMA4GA1UECAwHT250YXJpbzEnMCUGA1UEBwweTGVv
#bmFyZG8gV29ybGR3aWRlIENvcnBvcmF0aW9uMRQwEgYDVQQKDAtUZWFtIFJvY2tl
#dDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
#CgKCAQEA0C125Hyvme6twvhWLny8xgkKhCK5nWb7vx0KVHxs/Auf4LcN2uz3INmN
#PYxaG/5pHNNn0U4p/t5sB6TsfP1o7d9w5tEX2rspE/JPvkc1HNkwtMy+153PaKIF
#19MBcm033pcsRL43BJIc27J9RoZROeWMlM5r9eMAPZdVHQpJe6pnOkkFRh4Wwtgo
#OQRCeMiOJcDoxVsITDe2CgUwSBTq+baJd5Q27+xkPXq1t1qr9oX7D9p2Z9wWFNn5
#HU72fiYtFLODsh2pSBhlKnVX37Qt844KtXE+COn0CTQXL9XsKSyRWqBvUhgh8I8o
#AaNWWmmO2jlSINx2TkCBzSzWKrOOjwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCj
#gfC1/M1hHj1Nhx+YZqqMnMGtHWDPPgY9odqO/V3LrB5E370sGtmzLXxNdIrY7jaZ
#zayRA3Fwm4mtKkM2Vd8ea1xNLm2/jjOt5DHNWVIJ7QY68ifllRPpddJwWtrwtRiX
#SawsF/YyW15I/RSTJ+s4NI1uH0tberZfCIVcxrlS70xzQlcSrJaI9ofwInBXEvp5
#jhlCh1mj+L9BEDtLj9kQbRhAIF7C6QNG3CK1lno/cBgclGWmsADr4TFipFYEVRuG
#EXDe8iMokc7S60ZBb8sIQmXEg2P1pgkV2+aM+64stOQqRmxY+gSc/EfA24P+8TMG
#C8VQ+6ApVAoupNTJQl8a
#-----END CERTIFICATE-----