grpc-connections:
  api-gateway-content-management:
    host: a9da3b8b2c36211e9845e0acab4f59b3-877756777.us-east-2.elb.amazonaws.com
    port: 6565
    tls-certificate-file-path: "/opt/apps/resource/mobias-mona-lisa-syndicator/certificate/leo-prd_generated-dns/ca/cacert.pem"
  api-gateway-hotel-management:
    host: mobias-mona-lisa-api-gateway.app.leonardo.com
    port: 6565
    tls-certificate-file-path: "/opt/apps/resource/mobias-mona-lisa-syndicator/certificate/leo-prd_external-dns/ca/cacert.pem"
  hotel-management:
    host: 127.0.0.1
    port: 6565
    tls-certificate-file-path: ""
  content-management:
    host: 127.0.0.1
    port: 6565
    tls-certificate-file-path: ""
