grpc-connections:
  content-management:
    host: a9da3b8b2c36211e9845e0acab4f59b3-877756777.us-east-2.elb.amazonaws.com
    port: 6565
    tls-certificate-file-path: "/opt/apps/resource/mobias-mona-lisa-syndicator/certificate/leo-prd_generated-dns/ca/cacert.pem"
  hotel-management:
    host: a9da3b8b2c36211e9845e0acab4f59b3-877756777.us-east-2.elb.amazonaws.com
    port: 6565
    tls-certificate-file-path: "/opt/apps/resource/mobias-mona-lisa-syndicator/certificate/leo-prd_generated-dns/ca/cacert.pem"
